const ROUTER = "";

export const ROUTER_NAME = {
  LOGIN: "",
  DASHBOARD: "dashboard",
  BOOKINGS: "bookings",
  PROVIDERS: "providers",
  TRIPS: "trips",
  ROUTES: "routes",
  VEHICLES: "vehicles",
  CUSTOMERS: "customers",
  DRIVERS: "drivers",
  REVENUE: "revenue",
  REPORTS: "reports",
  CHAT: "chat",
  NOT_FOUND: "*",
};

export const ROUTER_PATH = {
  LOGIN: `${ROUTER}/${ROUTER_NAME.LOGIN}`,
  DASHBOARD: `${ROUTER}/${ROUTER_NAME.DASHBOARD}`,
  BOOKINGS: `${ROUTER}/${ROUTER_NAME.BOOKINGS}`,
  PROVIDERS: `${ROUTER}/${ROUTER_NAME.PROVIDERS}`,
  TRIPS: `${ROUTER}/${ROUTER_NAME.TRIPS}`,
  ROUTES: `${ROUTER}/${ROUTER_NAME.ROUTES}`,
  VEHICLES: `${ROUTER}/${ROUTER_NAME.VEHICLES}`,
  CUSTOMERS: `${ROUTER}/${ROUTER_NAME.CUSTOMERS}`,
  DRIVERS: `${ROUTER}/${ROUTER_NAME.DRIVERS}`,
  REVENUE: `${ROUTER}/${ROUTER_NAME.REVENUE}`,
  REPORTS: `${ROUTER}/${ROUTER_NAME.REPORTS}`,
  CHAT: `${ROUTER}/${ROUTER_NAME.CHAT}`,
  NOT_FOUND: `${ROUTER}/${ROUTER_NAME.NOT_FOUND}`,
};
